require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3.2
  NewCops: enable
  Exclude:
   - test.rb

Layout/LineLength:
  Max: 100

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyleForEmptyBraces: space

Lint/EmptyBlock:
  Exclude:
   - spec/rubydium/mixins/command_macros_spec.rb

Metrics/BlockLength:
  Exclude:
   - spec/**/*

Metrics/MethodLength:
  CountAsOne:
   - array
   - heredoc
   - method_call
   - hash

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
